### ISSUE TITLE
MelonLoader

### ISSUE THREAD

**Issue by Murugan47** [wafflethings/muckhack#1]
It isn't being detected by melon loader in the mods folder, can I get a .dll file or some help?

**Comment by HTDBarsi** [comment]
make sure you have 0.3.0 installed:
https://media.discordapp.net/attachments/807109298982354955/810352859539439646/geuCSLseKf.gif

dll:
https://github.com/wafflethings/muckhack/releases/tag/Release

**Comment by wafflethings** [comment]
Use version 3.0.
